### PR TITLE
chore: update normalize function

### PR DESCRIPTION
**Pull request by donni106**
- added `Dimension` to adjust to the dimensions of the device
- integrated the function used in the `react-native-size-metters` package

SVA-1351

Simulator Screen Shot - iPhone SE (3rd generation) - 2024-05-28 at 16 25 38-tile

### CODE REVIEW

**Comment by d4v3d4vE** [comment]
ich denke um Geräte mit unterschiedlichen Seitenverhältnissen abdecken zu können, sollten wir auch guidelineBaseHeight in den Code miteinbeziehen, als auch die PixelRatio. 

Hier ist ein Code Beispiel:

`import { Dimensions, PixelRatio } from 'react-native';

const guidelineBaseWidth = 393;
const guidelineBaseHeight = 852;

export const normalize = (size, factor = 1) => {
  const { width, height } = Dimensions.get('window');
  const widthScale = width / guidelineBaseWidth;
  const heightScale = height / guidelineBaseHeight;
  const scale = Math.min(widthScale, heightScale); // Nimmt das kleinere Verhältnis, um Übermaß zu vermeiden

  const newSize = size * scale;
  return PixelRatio.roundToNearestPixel(newSize * factor);
};
`

**Review by d4v3d4vE — COMMENTED** [review]
I think to cover devices with different aspect ratios, we should also include `guidelineBaseHeight` in the code, as well as `PixelRatio`.

Here is a code example:
```
import { Dimensions, PixelRatio } from 'react-native';

const guidelineBaseWidth = 393;
const guidelineBaseHeight = 852;

export const normalize = (size, factor = 1) => {
const { width, height } = Dimensions.get('window');
const widthScale = width / guidelineBaseWidth;
const heightScale = height / guidelineBaseHeight;
const scale = Math.min(widthScale, heightScale); // Takes the smaller ratio to avoid excess.

const newSize = size * scale;
return PixelRatio.roundToNearestPixel(newSize * factor);
};
```

worked it out with an idea I had and ChatGPT

**Comment by ardasnturk** [comment]
> I think to cover devices with different aspect ratios, we should also include `guidelineBaseHeight` in the code, as well as `PixelRatio`.
> 
> Here is a code example:
> 
> ```
> import { Dimensions, PixelRatio } from 'react-native';
> 
> const guidelineBaseWidth = 393;
> const guidelineBaseHeight = 852;
> 
> export const normalize = (size, factor = 1) => {
>    const { width, height } = Dimensions.get('window');
>    const widthScale = width / guidelineBaseWidth;
>    const heightScale = height / guidelineBaseHeight;
>    const scale = Math.min(widthScale, heightScale); // Takes the smaller ratio to avoid excess.
> 
>    const newSize = size * scale;
>    return PixelRatio.roundToNearestPixel(newSize * factor);
> };
> ```
> 
> worked it out with an idea I had and ChatGPT

Did you try this code? How does it contribute to the UI? How does it look?

**Comment by d4v3d4vE** [comment]
> > I think to cover devices with different aspect ratios, we should also include `guidelineBaseHeight` in the code, as well as `PixelRatio`.
> > Here is a code example:
> > ```
> > import { Dimensions, PixelRatio } from 'react-native';
> > 
> > const guidelineBaseWidth = 393;
> > const guidelineBaseHeight = 852;
> > 
> > export const normalize = (size, factor = 1) => {
> >    const { width, height } = Dimensions.get('window');
> >    const widthScale = width / guidelineBaseWidth;
> >    const heightScale = height / guidelineBaseHeight;
> >    const scale = Math.min(widthScale, heightScale); // Takes the smaller ratio to avoid excess.
> > 
> >    const newSize = size * scale;
> >    return PixelRatio.roundToNearestPixel(newSize * factor);
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > worked it out with an idea I had and ChatGPT
> 
> Did you try this code? How does it contribute to the UI? How does it look?

Yes I tried it briefly and it looks fine, takes in account all aspect ratios of devices for positioning with normalize and not just the width.

**Comment by donni106** [comment]
@d4v3d4vE please create a branch from `chore/SVA-1351-update-normalize`, add your changes and open a pull request with the same screenshots i provided here. in that new PR we can discuss the code directly on the changed lines, instead of quoting comments here.

**Review by ardasnturk — APPROVED** [review]

**Pull request merged**
